'use client';

import { FormEvent } from 'react';
import type { Product } from '@/lib/api';
import { createAdminProductVariant, deleteAdminProductVariant, updateAdminProductVariant } from '@/lib/api';

const toCents = (value: FormDataEntryValue | null) => value ? Math.round(Number(value) * 100) : null;
const toRsd = (value?: number | null) => value ? String(value / 100) : '';

export function AdminProductVariants({ token, product, onChanged }: { token: string; product: Product; onChanged: () => Promise<void> }) {
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await createAdminProductVariant(token, product.id, { sku: String(form.get('sku') || '') || null, size: String(form.get('size') || '') || null, color: String(form.get('color') || '') || null, price_cents: toCents(form.get('price')), stock_quantity: Number(form.get('stock_quantity') || 0), is_active: true }); event.currentTarget.reset(); await onChanged(); }
  return <div className="space-y-3 border border-slate-200 p-3"><h4 className="font-semibold">Varijante</h4><form onSubmit={add} className="grid gap-2 md:grid-cols-6"><input name="size" placeholder="Veličina" className="border px-2 py-2" /><input name="color" placeholder="Boja" className="border px-2 py-2" /><input name="sku" placeholder="SKU" className="border px-2 py-2" /><input name="price" type="number" step="0.01" placeholder="Cena RSD" className="border px-2 py-2" /><input name="stock_quantity" type="number" min="0" defaultValue={0} className="border px-2 py-2" /><button className="bg-primary px-3 py-2 text-white">Dodaj</button></form><div className="space-y-2">{product.variants.map((variant) => <form key={variant.id} onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await updateAdminProductVariant(token, product.id, variant.id, { size: String(form.get('size') || '') || null, color: String(form.get('color') || '') || null, sku: String(form.get('sku') || '') || null, price_cents: toCents(form.get('price')), stock_quantity: Number(form.get('stock_quantity') || 0), is_active: form.get('is_active') === 'on' }); await onChanged(); }} className="grid gap-2 text-sm md:grid-cols-7"><input name="size" defaultValue={variant.size ?? ''} className="border px-2 py-1" /><input name="color" defaultValue={variant.color ?? ''} className="border px-2 py-1" /><input name="sku" defaultValue={variant.sku ?? ''} className="border px-2 py-1" /><input name="price" type="number" step="0.01" defaultValue={toRsd(variant.price_cents)} className="border px-2 py-1" /><input name="stock_quantity" type="number" defaultValue={variant.stock_quantity} className="border px-2 py-1" /><label><input name="is_active" type="checkbox" defaultChecked={variant.is_active} /> active</label><span className="flex gap-2"><button className="border px-2 py-1">Snimi</button><button type="button" onClick={async () => { await deleteAdminProductVariant(token, product.id, variant.id); await onChanged(); }} className="border px-2 py-1 text-red-700">Delete</button></span></form>)}</div></div>;
}
