'use client';

import { FormEvent } from 'react';
import type { Product } from '@/lib/api';
import { createAdminProductImage, deleteAdminProductImage, setPrimaryAdminProductImage } from '@/lib/api';

export function AdminProductImages({ product, onChanged }: { product: Product; onChanged: () => Promise<void> }) {
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await createAdminProductImage(product.id, { image_url: String(form.get('image_url')), alt_text: String(form.get('alt_text') || '') || null, sort_order: Number(form.get('sort_order') || 0) }); event.currentTarget.reset(); await onChanged(); }
  return <div className="space-y-3 border border-slate-200 p-3"><div><h4 className="font-semibold">Slike</h4><p className="text-xs text-slate-500">Unesite eksterni image_url. Alt tekst je preporučen za SEO i pristupačnost.</p></div><form onSubmit={add} className="grid gap-2 md:grid-cols-4"><input name="image_url" required placeholder="https://..." className="border px-2 py-2" /><input name="alt_text" placeholder="Alt tekst (preporučeno)" className="border px-2 py-2" /><input name="sort_order" type="number" defaultValue={0} className="border px-2 py-2" /><button className="bg-primary px-3 py-2 text-white">Dodaj sliku</button></form><ul className="space-y-2">{product.images.map((image) => <li key={image.id} className="grid gap-3 rounded-2xl border border-slate-100 p-3 text-sm md:grid-cols-[72px_1fr_auto]"><img src={image.image_url} alt={image.alt_text ?? product.name} className="h-16 w-16 rounded-xl bg-slate-100 object-cover" /><div className="min-w-0"><span className="font-medium">#{image.sort_order}</span><p className="truncate text-slate-500">{image.image_url}</p><p className="text-slate-500">Alt: {image.alt_text || 'nije unet'}</p>{image.is_primary && <span className="inline-block bg-green-100 px-2 py-1 text-green-800">primarna</span>}</div><div className="flex flex-wrap items-center gap-2"><button onClick={async () => { await setPrimaryAdminProductImage(product.id, image.id); await onChanged(); }} className="border px-2 py-1">Primarna slika</button><button onClick={async () => { await deleteAdminProductImage(product.id, image.id); await onChanged(); }} className="border px-2 py-1 text-red-700">Obriši</button></div></li>)}</ul></div>;
}
