import Link from 'next/link';
import type { Product } from '@/lib/api';
import { AddToCartButton } from './AddToCartButton';
import { Price } from './Price';

export function ProductCard({ product }: { product: Product }) {
  const sortedImages = [...(product.images ?? [])].sort((a, b) => Number(b.is_primary) - Number(a.is_primary) || a.sort_order - b.sort_order || a.id - b.id);
  const image = sortedImages[0]?.image_url ?? product.image_url;
  const stock = product.effective_stock_quantity ?? product.stock_quantity;
  const hasVariants = product.variants?.some((variant) => variant.is_active) ?? false;
  return <article className="group flex h-full flex-col overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><Link href={`/products/${product.slug}`} className="relative block aspect-[4/5] bg-slate-100">{image ? <img src={image} alt={product.name} className="h-full w-full object-cover transition group-hover:scale-105" /> : <div className="flex h-full items-center justify-center px-6 text-center text-sm text-slate-500">Slika proizvoda uskoro</div>}{stock <= 0 && <span className="absolute left-3 top-3 rounded-full bg-slate-900 px-3 py-1 text-xs font-semibold text-white">Nema na stanju</span>}{product.compare_at_price_cents && product.compare_at_price_cents > product.price_cents && <span className="absolute right-3 top-3 rounded-full bg-gold px-3 py-1 text-xs font-semibold text-primary">Akcija</span>}</Link><div className="flex flex-1 flex-col p-5"><p className="text-sm text-slate-500">{product.category?.name ?? product.sku ?? 'Simeon Shop'}</p><Link href={`/products/${product.slug}`} className="mt-1 text-lg font-semibold text-primary hover:underline">{product.name}</Link>{product.short_description && <p className="mt-2 line-clamp-2 text-sm text-slate-600">{product.short_description}</p>}<div className="mt-3 flex items-baseline gap-2"><p className="font-bold"><Price cents={product.price_cents} currency={product.currency} /></p>{product.compare_at_price_cents && product.compare_at_price_cents > product.price_cents && <p className="text-sm text-slate-400 line-through"><Price cents={product.compare_at_price_cents} currency={product.currency} /></p>}</div><div className="mt-auto pt-4">{hasVariants ? <Link href={`/products/${product.slug}`} className="block w-full bg-primary px-4 py-3 text-center text-sm font-semibold text-white">Izaberi varijantu</Link> : <AddToCartButton product={product} />}</div></div></article>;
}
